apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: duniversity-ns
spec:
  replicas: 1
  strategy:
    typs: RollingUpdate
    rollingUpdate:
      maxUnavilable: 1
      maxSurge: 1
    selector:
      matchLabels:
        app: mysql
    template:
      metadata:
        labels: 
          app: mysql
      spes:
        containers:
        - name: backend-cont
          image: mariadb
          ports:
          - containerPort: 3306
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"
            requests:
              memory: "256Mi"
              cpu: "100m"
          envForm:
          - configMapRef:
              name: duniversity-config 
          - secertRef:
              name: duniversity-secret

    