apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: pavi-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels: 
        app: mysql
    spec:

      # # ✅ NODE AFFINITY (DB should run on specific node)
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: disktype       # ⚠️ change based on your node label
      #           operator: In
      #           values:
      #           - ssd

      containers:
      - name: mysql-cont   
        image: mariadb
        ports:
        - containerPort: 3306

        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
          requests:
            memory: "256Mi"
            cpu: "100m"   

      #   envFrom:
      #     - configMapRef:
      #         name: duniversity-config 
      #     - secretRef:
      #         name: duniversity-secret

      #   volumeMounts:
      #   - name: mysql-storage
      #     mountPath: /var/lib/mysql
      #   - name: init-script
      #     mountPath: /docker-entrypoint-initdb.d

      # volumes:
      # - name: mysql-storage
      #   persistentVolumeClaim:
      #     claimName: mysql-pvc
      # - name: init-script
      #   configMap:
      #     name: mysql-init-script