apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: pavi-ns
spec:
  accessModes:
    - ReadWriteMany   
  storageClassName: university-storage
  resources:
    requests:
      storage: 5Gi