apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: university-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.2.222
  share: /mnt/data/duniversity
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true