apiVersion: apps/v1
kind: Deployment
metadata:
  Nname: {{ .Values.app.name }}
  namespace: pavi-ns
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: duniversity-app
  template:
    metadata:
      labels:
        app: duniversity-app
    spec:
      containers:
        - name: dunivesrity-cont
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.ports.containerPort }}
          resources:
            limits:
              cpu: "200m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"   

