apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pavi-ns
  name: pavithra-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]    