apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pavithra-rb
  namespace: pavi-ns
subjects:
- kind: User
  name: raj
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: pavithra-ns
  namespace: pavi-ns
roleRef:
  kind: Role
  name: pavithra-role
  apiGroup: rbac.authorization.k8s.io